create table MDMUNITS(
	SPESORTS      VARCHAR2(10),
	PRODUCTCD  VARCHAR2(36),
	CLASSCD        VARCHAR2(50),
	RECSTATUS    CHAR(1),
	RECCREATETIME DATE,
	RECUPDATETIME DATE,
	PRIMARY KEY (PRODUCTCD) 
);