create table MDMMATSORTS(
	SPESORTS   VARCHAR2(5),
	MATERIALSORTNM VARCHAR2(36),
	CLASSCD  VARCHAR2(20),
	CLASSNM VARCHAR2(20),
	PARENTCLASSCD VARCHAR2(20),
	CLASSLEVEL  CHAR(1),
	STOPFLAG     CHAR(1),
	RECSTATUS    CHAR(1),
	RECCREATETIME DATE,
	RECUPDATETIME DATE,
	PRIMARY KEY (MATERIALSORTNM)
);