create table MDMUNITS(
	UNITCD  VARCHAR2(36),
	UNITNM VARCHAR2(10),
	SSNM      VARCHAR2(10),
	RECSTATUS  CHAR(1),
	STOPFLAG    CHAR(1),
	RECCREATETIME  DATE,
	RECUPDATETIME DATE,
	PRIMARY KEY (UNITNM) 
);